### ISSUE TITLE
Hard disk 

### ISSUE THREAD

**Issue by abhishekbs111** [jmalarcon/Asusnova#1]
Hi sir,
I want your help. I have this same cpu that you are talking about. Few days back few some ants entered in my cpu so i opened it and gently removed them without touching any parts of my cpu, after cleaning i turned on the cpu, it was showing no operating system. So i tried to install new windows, and when i reached the disk partition page of the windows setup i found it was not showing my hard disk space. I very helpless. Please help, tell me the possible problem and their solution.

**Comment by jmalarcon** [comment]
Hi:

Sorry, I can't help you with that. It seems a problem with the Operating System, not the hardware, and I don't have a clue on what could be wrong in this case. Sometimes disks got screwed without a very good reason. Maybe simply is a very old disk or maybe one of those ants could make it inside the disk and messed with the magnetic sectors, specially if the data is inside it but not accesible.

Instead of reinstalling Windows I'd go trying to [restore the Master Boot Record of the disk](https://neosmart.net/wiki/fix-mbr/). If not, the best thing you can do is take your computer to an specialized shop and pay them for fixing it.

Sorry not being more helpful in this case.

Good luck!
